<?php

/**
 * @file
 * Creates custom Site Studio elements.
 */

/**
 * Implements hook_theme().
 */
function site_studio_custom_elements_theme($existing, $type, $theme, $path) {
  return [
    'site_studio_custom_elements' => [
      'template' => 'api-data-element-template',
      'variables' => [
        'elementSettings' => NULL,
        'elementMarkup' => NULL,
        'elementContext' => NULL,
        'elementClass' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
